bot-token: #go to https://discord.com/developers/applications, create a new application, go to bot, create a new bot and paste the token here
discord-chat-channelid: #<-- this is the channel you can chat in with other people